name: simplabs.com

sass:
  sass_dir: css

gems:
  - jekyll-sitemap

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

excerpt_separator: <!--break-->
  
navigation:
  - title: Services
    url: /services/
  - title: Process
    url: /process/
  - title: About
    url: /about/
  - title: Clients
    url: /clients/
  - title: Blog
    url: /blog/
