name: simplabs.com

sass:
  sass_dir: css

gems:
  - jekyll-sitemap

navigation:
  - title: "&nbsp;"
    url: /
    file: /index.html
    class: logo
  - title: Cases
    url: /cases
    file: /cases/index.html
    class:
  - title: Contact
    url: /contact
    file: /contact/index.html
    class:
    - title: About
    url: /about
    file: /about/index.html
    class:
    - title: Clients
    url: /clients
    file: /clients/index.html
    class:
  - title: Blog
    url: log.simplabs.com
    file: 
    class:
  