name: simplabs.com
highlighter: false

sass:
  sass_dir: css

navigation:
  - title: "&nbsp;"
    url: /
    file: /index.html
    class: logo
  - title: Who we are
    url: /who-we-are
    file: /who-we-are/index.html
    class:
  - title: What we do
    url: /what-we-do
    file: /what-we-do/index.html
    class:
  - title: What we use
    url: /what-we-use
    file: /what-we-use/index.html
    class:
  - title: Clients
    url: /clients
    file: /clients/index.html
    class:
